########################################################################################
# Trigger the examples rendering in the external repository.
#
# This task push an empty commit to trigger the rendering of the example gallery
# in an external repo as follows:
#
# ------------------------------------------
# | Local branch -> Example gallery branch |
# | master       -> main                   |
# | other_branch -> dev                    |
# ------------------------------------------
#
# This workflow requires the EXAMPLES_GALLERY_TOKEN secret with the access token
# for the repository containing the example gallery.
########################################################################################
name: Trigger example rendering tasks in the external repository

env:
  EXAMPLES_GALLERY_REPO: pysteps/pysteps-tutorials # External repository with the example gallery.
  THIS_REPO: pysteps/pysteps

on:
  push:
    branches: [ master, dev, external_gallery]
#  pull_request:
#    branches: [ master, dev ]

jobs:
  trigger_example_gallery_rendering:
    name: Trigger example rendering tasks in the external repository
    # The triggering is done by pushing an empty commit to the external repository
    # with the example gallery. The commit message contains the Hash of the
    # main repository's commit and the branch name that trigger the event.
    runs-on: "ubuntu-latest"

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Get the name of the branch triggering this event
        id: get_triggering_branch
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
            event_branch=$(echo ${GITHUB_REF##*/})
          elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            event_branch=$(echo $GITHUB_BASE_REF)
          else
            event_branch=unknown
          fi
          echo "::set-output name=event_branch::${event_branch}"

      - name: Set destination branch based on the triggering branch's name
        id: set_destination_branch
        run: |
          # We only push to latest or to dev.
          if [[ "${event_branch}" == "main" ]]; then
            echo "::set-output name=dest_branch::main"
          else
            echo "::set-output name=dest_branch::dev"
          fi

      - name: Print debug information
        env:
          DEST_BRANCH: ${{steps.set_destination_branch.outputs.dest_branch}}
          EVENT_BRANCH: ${{steps.get_triggering_branch.outputs.event_branch}}
        run: |
          echo "EVENT_BRANCH=${EVENT_BRANCH}"
          echo "GITHUB_SHA=${GITHUB_SHA}"
          echo "DEST_BRANCH=${DEST_BRANCH}"

      - name: Clone external repository with the example gallery.
        uses: actions/checkout@v2
        with:
          persist-credentials: false # Avoid using the GITHUB_TOKEN  instead of the personal access token
          fetch-depth: 0 # Avoid errors pushing refs to the destination repository.
          repository: ${{ env.EXAMPLES_GALLERY_REPO }}
          ref: ${{steps.set_destination_branch.outputs.dest_branch}}

      - name: Create empty commit in example gallery's repository
        env:
          EVENT_BRANCH: ${{steps.get_triggering_branch.outputs.event_branch}}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit --allow-empty \
            -m "[TRIGGER] Trigger rendering task from ${GITHUB_SHA::8}" \
            -m "Branch:${EVENT_BRANCH}" \
            -m "https://github.com/${THIS_REPO}/commit/${GITHUB_SHA}"            

      - name: Push the empty commit to trigger the workflow
        uses: ad-m/github-push-action@master
        with:
          repository: ${{ env.EXAMPLES_GALLERY_REPO }}
          github_token: ${{ secrets.EXAMPLES_GALLERY_TOKEN }}
          branch: ${{steps.set_destination_branch.outputs.dest_branch}}
